---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
     name: "{{ packages }}"
     state: present
     update_cache: yes
    vars:
     packages:
     - apt-transport-https
     - ca-certificates
     - curl
     - gnupg-agent
     - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt:
     name: "{{ packages }}"
     state: present
     update_cache: yes
    vars:
     packages:
     - docker-ce
     - docker-ce-cli
     - containerd.io
    notify:
     - docker status

  - name: Add user to docker group
    user:
     name: ubuntu
     group: docker

  - name: Set user variable
    shell: uname -m
    register: uname

  - name: Install docker compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-{{ uname.stdout }}
      dest: /usr/bin/docker-compose
      mode: '0755'

  - name: Git Update
    git:
      repo: https://github.com/shdkej/odoo_gvm.git
      dest: /src/odoo_gvm
      update: yes

  - name: Docker-compose up
    shell: docker-compose -f /src/odoo_gvm/docker-compose-prod.yml up -d --build

  handlers:
  - name: docker status
    service: name=docker state=started
