Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "v"
#    ansible.playbook = "playbook.yml"
#  end

  config.vm.hostname = "gvm"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.synced_folder "~/Downloads", "/vagrant_data"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision "shell", path: "init.sh"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
